// Writes docs/COVERAGE.md: every mishna in Ohalos, its status, and its scenarios with results.
// Run with `npm run coverage-report`.
import { writeFileSync } from 'node:fs';
import { evaluate } from '../src/engine/evaluate';
import { COVERAGE } from '../src/scenes/coverage';
import { SCENARIOS } from '../src/scenes/index';
import type { Expectation } from '../src/scenes/types';

function passes(id: string): boolean {
  const s = SCENARIOS.find((x) => x.id === id)!;
  const ev = evaluate(s.scene(), s.shittos);
  return Object.entries(s.expect).every(([oid, want]: [string, Expectation]) => {
    const r = ev.objects[oid];
    const tamei = r?.status === 'tamei';
    if (want === 'tahor') return !tamei;
    if (want === 'tamei') return tamei;
    return tamei && (want === 'tamei7') === !!r.sevenDay;
  });
}

const ICON = { modeled: '🟢', partial: '🟡', todo: '⚪', catalog: '🔵' } as const;
const lines: string[] = [
  '# Coverage — Mishnah Ohalos',
  '',
  'Generated by `npm run coverage-report`. Every mishna is listed. A scenario is a 3D case with the',
  'mishna’s ruling; the engine must reproduce the ruling from its general rules.',
  '',
  '🟢 modeled · 🟡 partly modeled · ⚪ not yet modeled · 🔵 not spatial (tracked as data)',
  '',
];
const totals = { modeled: 0, partial: 0, todo: 0, catalog: 0 };
let pass = 0,
  fail = 0,
  pending = 0;
const body: string[] = [];
let chapter = 0;
for (const c of COVERAGE) {
  totals[c.status]++;
  const ch = Number(c.ref.split(':')[0]);
  if (ch !== chapter) {
    chapter = ch;
    body.push('', `## Chapter ${ch}`, '', '| Mishna | Status | Scenarios | Notes |', '| --- | --- | --- | --- |');
  }
  const scen = SCENARIOS.filter((s) => s.ref === c.ref);
  const cells = scen.map((s) => {
    if (s.status === 'pending') {
      pending++;
      return `⏳ ${s.id}`;
    }
    const ok = passes(s.id);
    if (ok) pass++;
    else fail++;
    return `${ok ? '✅' : '❌'} ${s.id}`;
  });
  body.push(`| ${c.ref} | ${ICON[c.status]} ${c.status} | ${cells.join('<br>') || '—'} | ${c.needs ?? ''} |`);
}
lines.push(
  `**${totals.modeled}** modeled, **${totals.partial}** partly modeled, **${totals.todo}** not yet modeled, **${totals.catalog}** not spatial — of ${COVERAGE.length} mishnayos.`,
  '',
  `Scenarios: **${pass}** passing, **${fail}** failing, **${pending}** pending.`,
  ...body,
  '',
);
writeFileSync(new URL('../docs/COVERAGE.md', import.meta.url), lines.join('\n'));
console.log(`coverage: ${pass} passing, ${fail} failing, ${pending} pending`);
if (fail) process.exit(1);
